# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_type', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='form',
            old_name='form_desc',
            new_name='form_description',
        ),
    ]
