# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleForm', '0003_auto_20171011_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_type',
            field=models.CharField(choices=[('Select', ''), ('Short', 'SH'), ('Single Choice', 'SC'), ('Multiple Choice', 'MC')], default='', max_length=20),
        ),
    ]
