# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleForm', '0004_auto_20171011_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_type',
            field=models.CharField(choices=[('', 'Select'), ('SH', 'Short'), ('SC', 'Single Choice'), ('MC', 'Multiple Choice')], default='', max_length=20),
        ),
    ]
