# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleForm', '0005_auto_20171011_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
