# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleForm', '0006_auto_20171011_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
