# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleForm', '0008_auto_20171011_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='form',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='GoogleForm.Option'),
        ),
    ]
