# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleForm', '0009_auto_20171013_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
    ]
