# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleForm', '0010_remove_question_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
