# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleForm', '0011_delete_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='user',
        ),
    ]
