# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleForm', '0013_auto_20171029_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='ques',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoogleForm.Question'),
        ),
    ]
