# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoogleForm', '0015_auto_20171106_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='total_ques',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
